// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2

package types

type ChangePostVisibilityRequest struct {
	PostId          string `path:"postId"`
	Visibility      string `json:"visibility"`
	ExpectedVersion uint64 `json:"expectedVersion"`
}

type ChangePostVisibilityResponse struct {
	PostId     string `json:"postId"`
	Visibility string `json:"visibility"`
	Version    uint64 `json:"version"`
	UpdatedAt  string `json:"updatedAt"`
}

type CreatePostRequest struct {
	Title          string           `json:"title,optional"`
	Content        string           `json:"content,optional"`
	Visibility     string           `json:"visibility"`
	Media          []PostMediaInput `json:"media,optional"`
	TagIds         []string         `json:"tagIds,optional"`
	PlaceIds       []string         `json:"placeIds,optional"`
	TripSnapshotId string           `json:"tripSnapshotId,optional"`
}

type CreatePostResponse struct {
	PostId  string `json:"postId"`
	Status  string `json:"status"`
	Version uint64 `json:"version"`
}

type DeletePostRequest struct {
	PostId          string `path:"postId"`
	ExpectedVersion uint64 `form:"expectedVersion"`
}

type DeletePostResponse struct {
	PostId    string `json:"postId"`
	Status    string `json:"status"`
	Version   uint64 `json:"version"`
	DeletedAt string `json:"deletedAt"`
}

type GetPostRequest struct {
	PostId string `path:"postId"`
}

type GetPostResponse struct {
	Id               string      `json:"id"`
	AuthorId         string      `json:"authorId"`
	Title            string      `json:"title"`
	Content          string      `json:"content"`
	Status           string      `json:"status"`
	Visibility       string      `json:"visibility"`
	Media            []PostMedia `json:"media"`
	Tags             []PostTag   `json:"tags"`
	PlaceIds         []string    `json:"placeIds"`
	TripSnapshotId   string      `json:"tripSnapshotId,optional"`
	LikeCount        uint64      `json:"likeCount"`
	FavoriteCount    uint64      `json:"favoriteCount"`
	CommentCount     uint64      `json:"commentCount"`
	LikedByRequester bool        `json:"likedByRequester"`
	SavedByRequester bool        `json:"savedByRequester"`
	Version          uint64      `json:"version"`
	PublishedAt      string      `json:"publishedAt,optional"`
	CreatedAt        string      `json:"createdAt"`
	UpdatedAt        string      `json:"updatedAt"`
}

type HealthResponse struct {
	Status string `json:"status"`
}

type ListMyPostsRequest struct {
	Cursor string `form:"cursor,optional"`
	Limit  int64  `form:"limit,default=20,range=[1:50]"`
	Status string `form:"status,optional"`
}

type ListMyPostsResponse struct {
	Items      []MyPostListItem `json:"items"`
	NextCursor string           `json:"nextCursor,optional"`
	HasMore    bool             `json:"hasMore"`
}

type ListPostsRequest struct {
	Cursor   string `form:"cursor,optional"`
	Limit    int64  `form:"limit,default=20,range=[1:50]"`
	AuthorId string `form:"authorId,optional"`
	TagId    string `form:"tagId,optional"`
	PlaceId  string `form:"placeId,optional"`
}

type ListPostsResponse struct {
	Items      []PostListItem `json:"items"`
	NextCursor string         `json:"nextCursor,optional"`
	HasMore    bool           `json:"hasMore"`
}

type MyPostListItem struct {
	Id          string    `json:"id"`
	Title       string    `json:"title"`
	Summary     string    `json:"summary"`
	Cover       PostMedia `json:"cover"`
	Status      string    `json:"status"`
	Visibility  string    `json:"visibility"`
	Version     uint64    `json:"version"`
	PublishedAt string    `json:"publishedAt,optional"`
	CreatedAt   string    `json:"createdAt"`
	UpdatedAt   string    `json:"updatedAt"`
}

type PostListItem struct {
	Id            string    `json:"id"`
	AuthorId      string    `json:"authorId"`
	Title         string    `json:"title"`
	Summary       string    `json:"summary"`
	Cover         PostMedia `json:"cover"`
	Tags          []PostTag `json:"tags"`
	LikeCount     uint64    `json:"likeCount"`
	FavoriteCount uint64    `json:"favoriteCount"`
	CommentCount  uint64    `json:"commentCount"`
	PublishedAt   string    `json:"publishedAt"`
}

type PostMedia struct {
	AssetId      string `json:"assetId"`
	SortOrder    int64  `json:"sortOrder"`
	Width        int64  `json:"width"`
	Height       int64  `json:"height"`
	ThumbnailUrl string `json:"thumbnailUrl"`
	LargeUrl     string `json:"largeUrl"`
}

type PostMediaInput struct {
	AssetId   string `json:"assetId"`
	SortOrder int64  `json:"sortOrder"`
}

type PostTag struct {
	Id   string `json:"id"`
	Name string `json:"name"`
}

type PublishPostRequest struct {
	PostId          string `path:"postId"`
	ExpectedVersion uint64 `json:"expectedVersion"`
}

type PublishPostResponse struct {
	PostId      string `json:"postId"`
	Status      string `json:"status"`
	Version     uint64 `json:"version"`
	PublishedAt string `json:"publishedAt"`
}

type UpdatePostRequest struct {
	PostId          string           `path:"postId"`
	ExpectedVersion uint64           `json:"expectedVersion"`
	Title           string           `json:"title,optional"`
	Content         string           `json:"content,optional"`
	Media           []PostMediaInput `json:"media,optional"`
	TagIds          []string         `json:"tagIds,optional"`
	PlaceIds        []string         `json:"placeIds,optional"`
	TripSnapshotId  string           `json:"tripSnapshotId,optional"`
}

type UpdatePostResponse struct {
	PostId    string `json:"postId"`
	Version   uint64 `json:"version"`
	UpdatedAt string `json:"updatedAt"`
}
