// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2

package types

type BatchGetPostCardsData struct {
	Items []PublishedPostCard `json:"items"`
}

type BatchGetPostCardsRequest struct {
	PostIds []string `json:"postIds"`
}

type BatchGetPostCardsResponse struct {
	ErrorCode int                   `json:"errorCode"`
	Message   string                `json:"message"`
	Data      BatchGetPostCardsData `json:"data,omitempty"`
	RequestId string                `json:"requestId,omitempty"`
}

type ChangePostVisibilityData struct {
	PostId      string `json:"postId"`
	Visibility  string `json:"visibility"`
	PostVersion uint64 `json:"postVersion"`
	UpdatedAt   string `json:"updatedAt"`
}

type ChangePostVisibilityRequest struct {
	PostId              string `path:"postId"`
	Visibility          string `json:"visibility"`
	ExpectedPostVersion uint64 `json:"expectedPostVersion"`
}

type ChangePostVisibilityResponse struct {
	ErrorCode int                      `json:"errorCode"`
	Message   string                   `json:"message"`
	Data      ChangePostVisibilityData `json:"data,omitempty"`
	RequestId string                   `json:"requestId,omitempty"`
}

type CompleteImageUploadData struct {
	Asset MediaAssetView `json:"asset"`
}

type CompleteImageUploadRequest struct {
	AssetId string `path:"assetId"`
}

type CompleteImageUploadResponse struct {
	ErrorCode int                     `json:"errorCode"`
	Message   string                  `json:"message"`
	Data      CompleteImageUploadData `json:"data,omitempty"`
	RequestId string                  `json:"requestId,omitempty"`
}

type ContentBlock struct {
	BlockId       string   `json:"blockId"`
	ParentBlockId string   `json:"parentBlockId,optional"`
	BlockType     string   `json:"blockType"`
	SortOrder     int64    `json:"sortOrder"`
	Title         string   `json:"title,optional"`
	Text          string   `json:"text,optional"`
	AssetIds      []string `json:"assetIds,optional"`
}

type CoverInput struct {
	AssetId   string  `json:"assetId,optional"`
	FocusX    float64 `json:"focusX,optional"`
	FocusY    float64 `json:"focusY,optional"`
	CropStyle string  `json:"cropStyle,optional"`
}

type CoverView struct {
	AssetId      string  `json:"assetId,optional"`
	FocusX       float64 `json:"focusX,optional"`
	FocusY       float64 `json:"focusY,optional"`
	CropStyle    string  `json:"cropStyle,optional"`
	Width        int64   `json:"width,optional"`
	Height       int64   `json:"height,optional"`
	ThumbnailUrl string  `json:"thumbnailUrl,optional"`
	LargeUrl     string  `json:"largeUrl,optional"`
}

type CreateImageUploadData struct {
	AssetId   string `json:"assetId"`
	Status    string `json:"status"`
	UploadUrl string `json:"uploadUrl"`
	ExpiresAt string `json:"expiresAt"`
}

type CreateImageUploadRequest struct {
	FileName    string `json:"fileName"`
	MimeType    string `json:"mimeType"`
	FileSize    uint64 `json:"fileSize"`
	ContentHash string `json:"contentHash,optional"`
}

type CreateImageUploadResponse struct {
	ErrorCode int                   `json:"errorCode"`
	Message   string                `json:"message"`
	Data      CreateImageUploadData `json:"data,omitempty"`
	RequestId string                `json:"requestId,omitempty"`
}

type CreatePostData struct {
	PostId       string `json:"postId"`
	Status       string `json:"status"`
	PostVersion  uint64 `json:"postVersion"`
	DraftVersion uint64 `json:"draftVersion"`
	CreatedAt    string `json:"createdAt"`
}

type CreatePostRequest struct {
	Visibility string       `json:"visibility"`
	Title      string       `json:"title,optional"`
	Summary    string       `json:"summary,optional"`
	Cover      CoverInput   `json:"cover,optional"`
	Document   PostDocument `json:"document"`
	TagNames   []string     `json:"tagNames,optional"`
}

type CreatePostResponse struct {
	ErrorCode int            `json:"errorCode"`
	Message   string         `json:"message"`
	Data      CreatePostData `json:"data,omitempty"`
	RequestId string         `json:"requestId,omitempty"`
}

type CreatorPostCard struct {
	PostId                string    `json:"postId"`
	Title                 string    `json:"title"`
	Summary               string    `json:"summary"`
	HasCover              bool      `json:"hasCover"`
	Cover                 CoverView `json:"cover"`
	Status                string    `json:"status"`
	Visibility            string    `json:"visibility"`
	PostVersion           uint64    `json:"postVersion"`
	DraftVersion          uint64    `json:"draftVersion"`
	PublishedRevisionId   string    `json:"publishedRevisionId,optional"`
	HasUnpublishedChanges bool      `json:"hasUnpublishedChanges"`
	PublishedAt           string    `json:"publishedAt,optional"`
	UpdatedAt             string    `json:"updatedAt"`
}

type DeleteMediaAssetData struct {
	AssetId   string `json:"assetId"`
	Status    string `json:"status"`
	DeletedAt string `json:"deletedAt"`
}

type DeleteMediaAssetRequest struct {
	AssetId string `path:"assetId"`
}

type DeleteMediaAssetResponse struct {
	ErrorCode int                  `json:"errorCode"`
	Message   string               `json:"message"`
	Data      DeleteMediaAssetData `json:"data,omitempty"`
	RequestId string               `json:"requestId,omitempty"`
}

type DeletePostData struct {
	PostId      string `json:"postId"`
	Status      string `json:"status"`
	PostVersion uint64 `json:"postVersion"`
	DeletedAt   string `json:"deletedAt"`
}

type DeletePostRequest struct {
	PostId              string `path:"postId"`
	ExpectedPostVersion uint64 `form:"expectedPostVersion"`
}

type DeletePostResponse struct {
	ErrorCode int            `json:"errorCode"`
	Message   string         `json:"message"`
	Data      DeletePostData `json:"data,omitempty"`
	RequestId string         `json:"requestId,omitempty"`
}

type GetPostData struct {
	PostId         string           `json:"postId"`
	AuthorId       string           `json:"authorId"`
	Status         string           `json:"status"`
	Visibility     string           `json:"visibility"`
	RevisionId     string           `json:"revisionId"`
	RevisionNumber uint64           `json:"revisionNumber"`
	Title          string           `json:"title"`
	Summary        string           `json:"summary"`
	HasCover       bool             `json:"hasCover"`
	Cover          CoverView        `json:"cover"`
	Document       PostDocument     `json:"document"`
	MediaAssets    []MediaAssetView `json:"mediaAssets"`
	Tags           []PostTag        `json:"tags"`
	LikeCount      uint64           `json:"likeCount"`
	FavoriteCount  uint64           `json:"favoriteCount"`
	CommentCount   uint64           `json:"commentCount"`
	PostVersion    uint64           `json:"postVersion"`
	PublishedAt    string           `json:"publishedAt"`
}

type GetPostDraftData struct {
	PostId       string           `json:"postId"`
	Status       string           `json:"status"`
	Visibility   string           `json:"visibility"`
	Title        string           `json:"title"`
	Summary      string           `json:"summary"`
	HasCover     bool             `json:"hasCover"`
	Cover        CoverView        `json:"cover"`
	Document     PostDocument     `json:"document"`
	MediaAssets  []MediaAssetView `json:"mediaAssets"`
	TagNames     []string         `json:"tagNames"`
	PostVersion  uint64           `json:"postVersion"`
	DraftVersion uint64           `json:"draftVersion"`
	UpdatedAt    string           `json:"updatedAt"`
}

type GetPostDraftRequest struct {
	PostId string `path:"postId"`
}

type GetPostDraftResponse struct {
	ErrorCode int              `json:"errorCode"`
	Message   string           `json:"message"`
	Data      GetPostDraftData `json:"data,omitempty"`
	RequestId string           `json:"requestId,omitempty"`
}

type GetPostRequest struct {
	PostId string `path:"postId"`
}

type GetPostResponse struct {
	ErrorCode int         `json:"errorCode"`
	Message   string      `json:"message"`
	Data      GetPostData `json:"data,omitempty"`
	RequestId string      `json:"requestId,omitempty"`
}

type HealthResponse struct {
	Status string `json:"status"`
}

type ListMyPostsData struct {
	Items      []CreatorPostCard `json:"items"`
	NextCursor string            `json:"nextCursor,optional"`
	HasMore    bool              `json:"hasMore"`
}

type ListMyPostsRequest struct {
	Cursor string `form:"cursor,optional"`
	Limit  int64  `form:"limit,default=20,range=[1:30]"`
	Status string `form:"status,optional"`
}

type ListMyPostsResponse struct {
	ErrorCode int             `json:"errorCode"`
	Message   string          `json:"message"`
	Data      ListMyPostsData `json:"data,omitempty"`
	RequestId string          `json:"requestId,omitempty"`
}

type ListPostsData struct {
	Items      []PublishedPostCard `json:"items"`
	NextCursor string              `json:"nextCursor,optional"`
	HasMore    bool                `json:"hasMore"`
}

type ListPostsRequest struct {
	Cursor string `form:"cursor,optional"`
	Limit  int64  `form:"limit,default=20,range=[1:30]"`
	TagId  string `form:"tagId,optional"`
}

type ListPostsResponse struct {
	ErrorCode int           `json:"errorCode"`
	Message   string        `json:"message"`
	Data      ListPostsData `json:"data,omitempty"`
	RequestId string        `json:"requestId,omitempty"`
}

type MediaAssetView struct {
	AssetId      string `json:"assetId"`
	MimeType     string `json:"mimeType"`
	Status       string `json:"status"`
	Width        int64  `json:"width"`
	Height       int64  `json:"height"`
	ThumbnailUrl string `json:"thumbnailUrl"`
	LargeUrl     string `json:"largeUrl"`
}

type PostDocument struct {
	SchemaVersion uint32         `json:"schemaVersion"`
	Blocks        []ContentBlock `json:"blocks"`
}

type PostTag struct {
	Id   string `json:"id"`
	Name string `json:"name"`
}

type PublishPostData struct {
	PostId         string `json:"postId"`
	RevisionId     string `json:"revisionId"`
	RevisionNumber uint64 `json:"revisionNumber"`
	Status         string `json:"status"`
	PostVersion    uint64 `json:"postVersion"`
	PublishedAt    string `json:"publishedAt"`
}

type PublishPostRequest struct {
	PostId               string `path:"postId"`
	ExpectedPostVersion  uint64 `json:"expectedPostVersion"`
	ExpectedDraftVersion uint64 `json:"expectedDraftVersion"`
}

type PublishPostResponse struct {
	ErrorCode int             `json:"errorCode"`
	Message   string          `json:"message"`
	Data      PublishPostData `json:"data,omitempty"`
	RequestId string          `json:"requestId,omitempty"`
}

type PublishedPostCard struct {
	PostId        string    `json:"postId"`
	RevisionId    string    `json:"revisionId"`
	AuthorId      string    `json:"authorId"`
	Visibility    string    `json:"visibility"`
	Title         string    `json:"title"`
	Summary       string    `json:"summary"`
	HasCover      bool      `json:"hasCover"`
	Cover         CoverView `json:"cover"`
	Tags          []PostTag `json:"tags"`
	LikeCount     uint64    `json:"likeCount"`
	FavoriteCount uint64    `json:"favoriteCount"`
	CommentCount  uint64    `json:"commentCount"`
	PostVersion   uint64    `json:"postVersion"`
	PublishedAt   string    `json:"publishedAt"`
}

type ReadinessResponse struct {
	Status   string `json:"status"`
	Database string `json:"database"`
}

type SavePostDraftData struct {
	PostId       string `json:"postId"`
	DraftVersion uint64 `json:"draftVersion"`
	UpdatedAt    string `json:"updatedAt"`
}

type SavePostDraftRequest struct {
	PostId               string       `path:"postId"`
	ExpectedDraftVersion uint64       `json:"expectedDraftVersion"`
	Title                string       `json:"title,optional"`
	Summary              string       `json:"summary,optional"`
	Cover                CoverInput   `json:"cover,optional"`
	Document             PostDocument `json:"document"`
	TagNames             []string     `json:"tagNames,optional"`
}

type SavePostDraftResponse struct {
	ErrorCode int               `json:"errorCode"`
	Message   string            `json:"message"`
	Data      SavePostDraftData `json:"data,omitempty"`
	RequestId string            `json:"requestId,omitempty"`
}

type SearchTagsData struct {
	Items []PostTag `json:"items"`
}

type SearchTagsRequest struct {
	Keyword string `form:"q"`
	Limit   int64  `form:"limit,default=20,range=[1:50]"`
}

type SearchTagsResponse struct {
	ErrorCode int            `json:"errorCode"`
	Message   string         `json:"message"`
	Data      SearchTagsData `json:"data,omitempty"`
	RequestId string         `json:"requestId,omitempty"`
}
