// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2

package types

type GetVerificationReq struct {
	PhoneNumber string `json:"phoneNumber"`
}

type GetVerificationResp struct {
	ErrorCode int    `json:"errorCode"`
	Message   string `json:"message"`
}

type LoginByPasswordReq struct {
	IdentifierType string `json:"identifierType"`
	Identifier     string `json:"identifier"`
	Password       string `json:"password"`
}

type LoginByPhoneReq struct {
	PhoneNumber      string `json:"phoneNumber"`
	VerificationCode string `json:"verificationCode"`
}

type LoginResp struct {
	ErrorCode        int    `json:"errorCode"`
	Message          string `json:"message"`
	UserID           string `json:"userId,omitempty"`
	AccessToken      string `json:"accessToken,omitempty"`
	RefreshToken     string `json:"refreshToken,omitempty"`
	AccessExpiresIn  int64  `json:"accessExpiresIn,omitempty"`
	RefreshExpiresIn int64  `json:"refreshExpiresIn,omitempty"`
}

type RegisterReq struct {
	UserName    string `json:"userName"`
	Password    string `json:"password"`
	PhoneNumber string `json:"phoneNumber"`
}

type RegisterResp struct {
	ErrorCode int    `json:"errorCode"`
	Message   string `json:"message"`
	UserID    string `json:"userId,omitempty"`
}
