// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2

package types

type DeviceInfo struct {
	DeviceID   string `json:"deviceId,omitempty"`
	DeviceName string `json:"deviceName"`
	Platform   string `json:"platform"`
	AppVersion string `json:"appVersion"`
}

type GetVerificationReq struct {
	PhoneNumber string `json:"phoneNumber"`
}

type GetVerificationResp struct {
	ErrorCode int    `json:"errorCode"`
	Message   string `json:"message"`
}

type LoginByPasswordReq struct {
	IdentifierType string     `json:"identifierType"`
	Identifier     string     `json:"identifier"`
	Password       string     `json:"password"`
	Device         DeviceInfo `json:"device"`
}

type LoginByPhoneReq struct {
	PhoneNumber      string     `json:"phoneNumber"`
	VerificationCode string     `json:"verificationCode"`
	Device           DeviceInfo `json:"device"`
}

type LoginResp struct {
	ErrorCode   int    `json:"errorCode"`
	Message     string `json:"message"`
	DeviceID    string `json:"deviceId,omitempty"`
	AccessToken string `json:"accessToken,omitempty"`
}

type LogoutResp struct {
	ErrorCode int    `json:"errorCode"`
	Message   string `json:"message"`
}

type RefreshResp struct {
	ErrorCode   int    `json:"errorCode"`
	Message     string `json:"message"`
	AccessToken string `json:"accessToken,omitempty"`
}

type RegisterReq struct {
	UserName    string `json:"userName"`
	Password    string `json:"password"`
	PhoneNumber string `json:"phoneNumber"`
}

type RegisterResp struct {
	ErrorCode int    `json:"errorCode"`
	Message   string `json:"message"`
	UserID    string `json:"userId,omitempty"`
}

type UserInfoResp struct {
	ErrorCode int    `json:"errorCode"`
	Message   string `json:"message"`
	UserID    string `json:"userId,omitempty"`
	Username  string `json:"username,omitempty"`
	Nickname  string `json:"nickname,omitempty"`
	AvatarURL string `json:"avatarUrl,omitempty"`
}
