// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	authorStateProjectionFieldNames          = builder.RawFieldNames(&AuthorStateProjection{})
	authorStateProjectionRows                = strings.Join(authorStateProjectionFieldNames, ",")
	authorStateProjectionRowsExpectAutoSet   = strings.Join(stringx.Remove(authorStateProjectionFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	authorStateProjectionRowsWithPlaceHolder = strings.Join(stringx.Remove(authorStateProjectionFieldNames, "`user_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	authorStateProjectionModel interface {
		Insert(ctx context.Context, data *AuthorStateProjection) (sql.Result, error)
		FindOne(ctx context.Context, userId string) (*AuthorStateProjection, error)
		Update(ctx context.Context, data *AuthorStateProjection) error
		Delete(ctx context.Context, userId string) error
	}

	defaultAuthorStateProjectionModel struct {
		conn  sqlx.SqlConn
		table string
	}

	AuthorStateProjection struct {
		UserId        string    `db:"user_id"`
		State         uint64    `db:"state"` // 1 active, 2 restricted, 3 disabled
		SourceVersion uint64    `db:"source_version"`
		UpdatedAt     time.Time `db:"updated_at"`
	}
)

func newAuthorStateProjectionModel(conn sqlx.SqlConn) *defaultAuthorStateProjectionModel {
	return &defaultAuthorStateProjectionModel{
		conn:  conn,
		table: "`author_state_projection`",
	}
}

func (m *defaultAuthorStateProjectionModel) Delete(ctx context.Context, userId string) error {
	query := fmt.Sprintf("delete from %s where `user_id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, userId)
	return err
}

func (m *defaultAuthorStateProjectionModel) FindOne(ctx context.Context, userId string) (*AuthorStateProjection, error) {
	query := fmt.Sprintf("select %s from %s where `user_id` = ? limit 1", authorStateProjectionRows, m.table)
	var resp AuthorStateProjection
	err := m.conn.QueryRowCtx(ctx, &resp, query, userId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAuthorStateProjectionModel) Insert(ctx context.Context, data *AuthorStateProjection) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, authorStateProjectionRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.State, data.SourceVersion)
	return ret, err
}

func (m *defaultAuthorStateProjectionModel) Update(ctx context.Context, data *AuthorStateProjection) error {
	query := fmt.Sprintf("update %s set %s where `user_id` = ?", m.table, authorStateProjectionRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.State, data.SourceVersion, data.UserId)
	return err
}

func (m *defaultAuthorStateProjectionModel) tableName() string {
	return m.table
}
