// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	mediaVariantFieldNames          = builder.RawFieldNames(&MediaVariant{})
	mediaVariantRows                = strings.Join(mediaVariantFieldNames, ",")
	mediaVariantRowsExpectAutoSet   = strings.Join(stringx.Remove(mediaVariantFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	mediaVariantRowsWithPlaceHolder = strings.Join(stringx.Remove(mediaVariantFieldNames, "`variant_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	mediaVariantModel interface {
		Insert(ctx context.Context, data *MediaVariant) (sql.Result, error)
		FindOne(ctx context.Context, variantId string) (*MediaVariant, error)
		FindOneByAssetIdVariantType(ctx context.Context, assetId string, variantType uint64) (*MediaVariant, error)
		Update(ctx context.Context, data *MediaVariant) error
		Delete(ctx context.Context, variantId string) error
	}

	defaultMediaVariantModel struct {
		conn  sqlx.SqlConn
		table string
	}

	MediaVariant struct {
		VariantId   string    `db:"variant_id"`
		AssetId     string    `db:"asset_id"`
		VariantType uint64    `db:"variant_type"` // 1 thumbnail, 2 large
		ObjectKey   string    `db:"object_key"`
		MimeType    string    `db:"mime_type"`
		FileSize    uint64    `db:"file_size"`
		Width       uint64    `db:"width"`
		Height      uint64    `db:"height"`
		Status      uint64    `db:"status"` // 1 processing, 2 ready, 3 failed, 4 deleted
		CreatedAt   time.Time `db:"created_at"`
		UpdatedAt   time.Time `db:"updated_at"`
	}
)

func newMediaVariantModel(conn sqlx.SqlConn) *defaultMediaVariantModel {
	return &defaultMediaVariantModel{
		conn:  conn,
		table: "`media_variant`",
	}
}

func (m *defaultMediaVariantModel) Delete(ctx context.Context, variantId string) error {
	query := fmt.Sprintf("delete from %s where `variant_id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, variantId)
	return err
}

func (m *defaultMediaVariantModel) FindOne(ctx context.Context, variantId string) (*MediaVariant, error) {
	query := fmt.Sprintf("select %s from %s where `variant_id` = ? limit 1", mediaVariantRows, m.table)
	var resp MediaVariant
	err := m.conn.QueryRowCtx(ctx, &resp, query, variantId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMediaVariantModel) FindOneByAssetIdVariantType(ctx context.Context, assetId string, variantType uint64) (*MediaVariant, error) {
	var resp MediaVariant
	query := fmt.Sprintf("select %s from %s where `asset_id` = ? and `variant_type` = ? limit 1", mediaVariantRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, assetId, variantType)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMediaVariantModel) Insert(ctx context.Context, data *MediaVariant) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, mediaVariantRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.VariantId, data.AssetId, data.VariantType, data.ObjectKey, data.MimeType, data.FileSize, data.Width, data.Height, data.Status)
	return ret, err
}

func (m *defaultMediaVariantModel) Update(ctx context.Context, newData *MediaVariant) error {
	query := fmt.Sprintf("update %s set %s where `variant_id` = ?", m.table, mediaVariantRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.AssetId, newData.VariantType, newData.ObjectKey, newData.MimeType, newData.FileSize, newData.Width, newData.Height, newData.Status, newData.VariantId)
	return err
}

func (m *defaultMediaVariantModel) tableName() string {
	return m.table
}
