// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	mediaAssetFieldNames          = builder.RawFieldNames(&MediaAsset{})
	mediaAssetRows                = strings.Join(mediaAssetFieldNames, ",")
	mediaAssetRowsExpectAutoSet   = strings.Join(stringx.Remove(mediaAssetFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	mediaAssetRowsWithPlaceHolder = strings.Join(stringx.Remove(mediaAssetFieldNames, "`asset_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	mediaAssetModel interface {
		Insert(ctx context.Context, data *MediaAsset) (sql.Result, error)
		FindOne(ctx context.Context, assetId string) (*MediaAsset, error)
		FindOneByOwnerIdUploadRequestId(ctx context.Context, ownerId string, uploadRequestId string) (*MediaAsset, error)
		FindOneByStorageProviderBucketNameObjectKey(ctx context.Context, storageProvider string, bucketName string, objectKey string) (*MediaAsset, error)
		Update(ctx context.Context, data *MediaAsset) error
		Delete(ctx context.Context, assetId string) error
	}

	defaultMediaAssetModel struct {
		conn  sqlx.SqlConn
		table string
	}

	MediaAsset struct {
		AssetId         string         `db:"asset_id"`
		OwnerId         string         `db:"owner_id"`
		UploadRequestId string         `db:"upload_request_id"`
		StorageProvider string         `db:"storage_provider"`
		BucketName      string         `db:"bucket_name"`
		ObjectKey       string         `db:"object_key"`
		MimeType        string         `db:"mime_type"`
		FileSize        uint64         `db:"file_size"`
		Width           sql.NullInt64  `db:"width"`
		Height          sql.NullInt64  `db:"height"`
		ContentHash     sql.NullString `db:"content_hash"`
		Status          uint64         `db:"status"` // 1 uploading, 2 processing, 3 ready, 4 failed, 5 deleted
		FailureCode     sql.NullString `db:"failure_code"`
		CreatedAt       time.Time      `db:"created_at"`
		UpdatedAt       time.Time      `db:"updated_at"`
		DeletedAt       sql.NullTime   `db:"deleted_at"`
	}
)

func newMediaAssetModel(conn sqlx.SqlConn) *defaultMediaAssetModel {
	return &defaultMediaAssetModel{
		conn:  conn,
		table: "`media_asset`",
	}
}

func (m *defaultMediaAssetModel) Delete(ctx context.Context, assetId string) error {
	query := fmt.Sprintf("delete from %s where `asset_id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, assetId)
	return err
}

func (m *defaultMediaAssetModel) FindOne(ctx context.Context, assetId string) (*MediaAsset, error) {
	query := fmt.Sprintf("select %s from %s where `asset_id` = ? limit 1", mediaAssetRows, m.table)
	var resp MediaAsset
	err := m.conn.QueryRowCtx(ctx, &resp, query, assetId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMediaAssetModel) FindOneByOwnerIdUploadRequestId(ctx context.Context, ownerId string, uploadRequestId string) (*MediaAsset, error) {
	var resp MediaAsset
	query := fmt.Sprintf("select %s from %s where `owner_id` = ? and `upload_request_id` = ? limit 1", mediaAssetRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, ownerId, uploadRequestId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMediaAssetModel) FindOneByStorageProviderBucketNameObjectKey(ctx context.Context, storageProvider string, bucketName string, objectKey string) (*MediaAsset, error) {
	var resp MediaAsset
	query := fmt.Sprintf("select %s from %s where `storage_provider` = ? and `bucket_name` = ? and `object_key` = ? limit 1", mediaAssetRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, storageProvider, bucketName, objectKey)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMediaAssetModel) Insert(ctx context.Context, data *MediaAsset) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, mediaAssetRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.AssetId, data.OwnerId, data.UploadRequestId, data.StorageProvider, data.BucketName, data.ObjectKey, data.MimeType, data.FileSize, data.Width, data.Height, data.ContentHash, data.Status, data.FailureCode, data.DeletedAt)
	return ret, err
}

func (m *defaultMediaAssetModel) Update(ctx context.Context, newData *MediaAsset) error {
	query := fmt.Sprintf("update %s set %s where `asset_id` = ?", m.table, mediaAssetRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.OwnerId, newData.UploadRequestId, newData.StorageProvider, newData.BucketName, newData.ObjectKey, newData.MimeType, newData.FileSize, newData.Width, newData.Height, newData.ContentHash, newData.Status, newData.FailureCode, newData.DeletedAt, newData.AssetId)
	return err
}

func (m *defaultMediaAssetModel) tableName() string {
	return m.table
}
