// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	outboxEventFieldNames          = builder.RawFieldNames(&OutboxEvent{})
	outboxEventRows                = strings.Join(outboxEventFieldNames, ",")
	outboxEventRowsExpectAutoSet   = strings.Join(stringx.Remove(outboxEventFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	outboxEventRowsWithPlaceHolder = strings.Join(stringx.Remove(outboxEventFieldNames, "`event_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	outboxEventModel interface {
		Insert(ctx context.Context, data *OutboxEvent) (sql.Result, error)
		FindOne(ctx context.Context, eventId string) (*OutboxEvent, error)
		Update(ctx context.Context, data *OutboxEvent) error
		Delete(ctx context.Context, eventId string) error
	}

	defaultOutboxEventModel struct {
		conn  sqlx.SqlConn
		table string
	}

	OutboxEvent struct {
		EventId       string       `db:"event_id"`
		AggregateType string       `db:"aggregate_type"`
		AggregateId   string       `db:"aggregate_id"`
		EventType     string       `db:"event_type"`
		PayloadJson   string       `db:"payload_json"`
		Status        uint64       `db:"status"` // 1 pending, 2 publishing, 3 published, 4 failed
		AttemptCount  uint64       `db:"attempt_count"`
		NextAttemptAt time.Time    `db:"next_attempt_at"`
		OccurredAt    time.Time    `db:"occurred_at"`
		PublishedAt   sql.NullTime `db:"published_at"`
		CreatedAt     time.Time    `db:"created_at"`
	}
)

func newOutboxEventModel(conn sqlx.SqlConn) *defaultOutboxEventModel {
	return &defaultOutboxEventModel{
		conn:  conn,
		table: "`outbox_event`",
	}
}

func (m *defaultOutboxEventModel) Delete(ctx context.Context, eventId string) error {
	query := fmt.Sprintf("delete from %s where `event_id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, eventId)
	return err
}

func (m *defaultOutboxEventModel) FindOne(ctx context.Context, eventId string) (*OutboxEvent, error) {
	query := fmt.Sprintf("select %s from %s where `event_id` = ? limit 1", outboxEventRows, m.table)
	var resp OutboxEvent
	err := m.conn.QueryRowCtx(ctx, &resp, query, eventId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultOutboxEventModel) Insert(ctx context.Context, data *OutboxEvent) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, outboxEventRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.EventId, data.AggregateType, data.AggregateId, data.EventType, data.PayloadJson, data.Status, data.AttemptCount, data.NextAttemptAt, data.OccurredAt, data.PublishedAt)
	return ret, err
}

func (m *defaultOutboxEventModel) Update(ctx context.Context, data *OutboxEvent) error {
	query := fmt.Sprintf("update %s set %s where `event_id` = ?", m.table, outboxEventRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.AggregateType, data.AggregateId, data.EventType, data.PayloadJson, data.Status, data.AttemptCount, data.NextAttemptAt, data.OccurredAt, data.PublishedAt, data.EventId)
	return err
}

func (m *defaultOutboxEventModel) tableName() string {
	return m.table
}
