// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	postStatsFieldNames          = builder.RawFieldNames(&PostStats{})
	postStatsRows                = strings.Join(postStatsFieldNames, ",")
	postStatsRowsExpectAutoSet   = strings.Join(stringx.Remove(postStatsFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	postStatsRowsWithPlaceHolder = strings.Join(stringx.Remove(postStatsFieldNames, "`post_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	postStatsModel interface {
		Insert(ctx context.Context, data *PostStats) (sql.Result, error)
		FindOne(ctx context.Context, postId string) (*PostStats, error)
		Update(ctx context.Context, data *PostStats) error
		Delete(ctx context.Context, postId string) error
	}

	defaultPostStatsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	PostStats struct {
		PostId        string    `db:"post_id"`
		LikeCount     uint64    `db:"like_count"`
		FavoriteCount uint64    `db:"favorite_count"`
		CommentCount  uint64    `db:"comment_count"`
		ViewCount     uint64    `db:"view_count"`
		SourceVersion uint64    `db:"source_version"`
		UpdatedAt     time.Time `db:"updated_at"`
	}
)

func newPostStatsModel(conn sqlx.SqlConn) *defaultPostStatsModel {
	return &defaultPostStatsModel{
		conn:  conn,
		table: "`post_stats`",
	}
}

func (m *defaultPostStatsModel) Delete(ctx context.Context, postId string) error {
	query := fmt.Sprintf("delete from %s where `post_id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, postId)
	return err
}

func (m *defaultPostStatsModel) FindOne(ctx context.Context, postId string) (*PostStats, error) {
	query := fmt.Sprintf("select %s from %s where `post_id` = ? limit 1", postStatsRows, m.table)
	var resp PostStats
	err := m.conn.QueryRowCtx(ctx, &resp, query, postId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPostStatsModel) Insert(ctx context.Context, data *PostStats) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, postStatsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.PostId, data.LikeCount, data.FavoriteCount, data.CommentCount, data.ViewCount, data.SourceVersion)
	return ret, err
}

func (m *defaultPostStatsModel) Update(ctx context.Context, data *PostStats) error {
	query := fmt.Sprintf("update %s set %s where `post_id` = ?", m.table, postStatsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.LikeCount, data.FavoriteCount, data.CommentCount, data.ViewCount, data.SourceVersion, data.PostId)
	return err
}

func (m *defaultPostStatsModel) tableName() string {
	return m.table
}
