// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	postFieldNames          = builder.RawFieldNames(&Post{})
	postRows                = strings.Join(postFieldNames, ",")
	postRowsExpectAutoSet   = strings.Join(stringx.Remove(postFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	postRowsWithPlaceHolder = strings.Join(stringx.Remove(postFieldNames, "`post_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	postModel interface {
		Insert(ctx context.Context, data *Post) (sql.Result, error)
		FindOne(ctx context.Context, postId string) (*Post, error)
		FindOneByAuthorIdCreateRequestId(ctx context.Context, authorId string, createRequestId string) (*Post, error)
		Update(ctx context.Context, data *Post) error
		Delete(ctx context.Context, postId string) error
	}

	defaultPostModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Post struct {
		PostId              string         `db:"post_id"`
		AuthorId            string         `db:"author_id"`
		CreateRequestId     string         `db:"create_request_id"`
		LifecycleStatus     uint64         `db:"lifecycle_status"`    // 1 draft, 2 publishing, 3 published, 4 deleted
		Visibility          uint64         `db:"visibility"`          // 1 public, 2 followers, 3 private
		AvailabilityStatus  uint64         `db:"availability_status"` // 1 normal, 2 pending, 3 hidden
		PublishedRevisionId sql.NullString `db:"published_revision_id"`
		PostVersion         uint64         `db:"post_version"`
		FirstPublishedAt    sql.NullTime   `db:"first_published_at"`
		LastPublishedAt     sql.NullTime   `db:"last_published_at"`
		CreatedAt           time.Time      `db:"created_at"`
		UpdatedAt           time.Time      `db:"updated_at"`
		DeletedAt           sql.NullTime   `db:"deleted_at"`
	}
)

func newPostModel(conn sqlx.SqlConn) *defaultPostModel {
	return &defaultPostModel{
		conn:  conn,
		table: "`post`",
	}
}

func (m *defaultPostModel) Delete(ctx context.Context, postId string) error {
	query := fmt.Sprintf("delete from %s where `post_id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, postId)
	return err
}

func (m *defaultPostModel) FindOne(ctx context.Context, postId string) (*Post, error) {
	query := fmt.Sprintf("select %s from %s where `post_id` = ? limit 1", postRows, m.table)
	var resp Post
	err := m.conn.QueryRowCtx(ctx, &resp, query, postId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPostModel) FindOneByAuthorIdCreateRequestId(ctx context.Context, authorId string, createRequestId string) (*Post, error) {
	var resp Post
	query := fmt.Sprintf("select %s from %s where `author_id` = ? and `create_request_id` = ? limit 1", postRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, authorId, createRequestId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPostModel) Insert(ctx context.Context, data *Post) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, postRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.PostId, data.AuthorId, data.CreateRequestId, data.LifecycleStatus, data.Visibility, data.AvailabilityStatus, data.PublishedRevisionId, data.PostVersion, data.FirstPublishedAt, data.LastPublishedAt, data.DeletedAt)
	return ret, err
}

func (m *defaultPostModel) Update(ctx context.Context, newData *Post) error {
	query := fmt.Sprintf("update %s set %s where `post_id` = ?", m.table, postRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.AuthorId, newData.CreateRequestId, newData.LifecycleStatus, newData.Visibility, newData.AvailabilityStatus, newData.PublishedRevisionId, newData.PostVersion, newData.FirstPublishedAt, newData.LastPublishedAt, newData.DeletedAt, newData.PostId)
	return err
}

func (m *defaultPostModel) tableName() string {
	return m.table
}
