// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	postRevisionFieldNames          = builder.RawFieldNames(&PostRevision{})
	postRevisionRows                = strings.Join(postRevisionFieldNames, ",")
	postRevisionRowsExpectAutoSet   = strings.Join(stringx.Remove(postRevisionFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	postRevisionRowsWithPlaceHolder = strings.Join(stringx.Remove(postRevisionFieldNames, "`revision_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	postRevisionModel interface {
		Insert(ctx context.Context, data *PostRevision) (sql.Result, error)
		FindOne(ctx context.Context, revisionId string) (*PostRevision, error)
		FindOneByPostIdPublishRequestId(ctx context.Context, postId string, publishRequestId string) (*PostRevision, error)
		FindOneByPostIdRevisionNumber(ctx context.Context, postId string, revisionNumber uint64) (*PostRevision, error)
		Update(ctx context.Context, data *PostRevision) error
		Delete(ctx context.Context, revisionId string) error
	}

	defaultPostRevisionModel struct {
		conn  sqlx.SqlConn
		table string
	}

	PostRevision struct {
		RevisionId            string          `db:"revision_id"`
		PostId                string          `db:"post_id"`
		RevisionNumber        uint64          `db:"revision_number"`
		SourceDraftVersion    uint64          `db:"source_draft_version"`
		PublishRequestId      string          `db:"publish_request_id"`
		Title                 string          `db:"title"`
		Summary               string          `db:"summary"`
		CoverAssetId          sql.NullString  `db:"cover_asset_id"`
		CoverFocusX           sql.NullFloat64 `db:"cover_focus_x"`
		CoverFocusY           sql.NullFloat64 `db:"cover_focus_y"`
		CoverCropStyle        string          `db:"cover_crop_style"`
		PresentationMode      uint64          `db:"presentation_mode"`
		DocumentSchemaVersion uint64          `db:"document_schema_version"`
		DocumentJson          string          `db:"document_json"`
		PlainText             string          `db:"plain_text"`
		RouteSnapshotId       sql.NullString  `db:"route_snapshot_id"`
		RouteSnapshotVersion  sql.NullInt64   `db:"route_snapshot_version"`
		BlockCount            uint64          `db:"block_count"`
		ImageCount            uint64          `db:"image_count"`
		PublishedAt           time.Time       `db:"published_at"`
		CreatedAt             time.Time       `db:"created_at"`
	}
)

func newPostRevisionModel(conn sqlx.SqlConn) *defaultPostRevisionModel {
	return &defaultPostRevisionModel{
		conn:  conn,
		table: "`post_revision`",
	}
}

func (m *defaultPostRevisionModel) Delete(ctx context.Context, revisionId string) error {
	query := fmt.Sprintf("delete from %s where `revision_id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, revisionId)
	return err
}

func (m *defaultPostRevisionModel) FindOne(ctx context.Context, revisionId string) (*PostRevision, error) {
	query := fmt.Sprintf("select %s from %s where `revision_id` = ? limit 1", postRevisionRows, m.table)
	var resp PostRevision
	err := m.conn.QueryRowCtx(ctx, &resp, query, revisionId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPostRevisionModel) FindOneByPostIdPublishRequestId(ctx context.Context, postId string, publishRequestId string) (*PostRevision, error) {
	var resp PostRevision
	query := fmt.Sprintf("select %s from %s where `post_id` = ? and `publish_request_id` = ? limit 1", postRevisionRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, postId, publishRequestId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPostRevisionModel) FindOneByPostIdRevisionNumber(ctx context.Context, postId string, revisionNumber uint64) (*PostRevision, error) {
	var resp PostRevision
	query := fmt.Sprintf("select %s from %s where `post_id` = ? and `revision_number` = ? limit 1", postRevisionRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, postId, revisionNumber)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPostRevisionModel) Insert(ctx context.Context, data *PostRevision) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, postRevisionRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.RevisionId, data.PostId, data.RevisionNumber, data.SourceDraftVersion, data.PublishRequestId, data.Title, data.Summary, data.CoverAssetId, data.CoverFocusX, data.CoverFocusY, data.CoverCropStyle, data.PresentationMode, data.DocumentSchemaVersion, data.DocumentJson, data.PlainText, data.RouteSnapshotId, data.RouteSnapshotVersion, data.BlockCount, data.ImageCount, data.PublishedAt)
	return ret, err
}

func (m *defaultPostRevisionModel) Update(ctx context.Context, newData *PostRevision) error {
	query := fmt.Sprintf("update %s set %s where `revision_id` = ?", m.table, postRevisionRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.PostId, newData.RevisionNumber, newData.SourceDraftVersion, newData.PublishRequestId, newData.Title, newData.Summary, newData.CoverAssetId, newData.CoverFocusX, newData.CoverFocusY, newData.CoverCropStyle, newData.PresentationMode, newData.DocumentSchemaVersion, newData.DocumentJson, newData.PlainText, newData.RouteSnapshotId, newData.RouteSnapshotVersion, newData.BlockCount, newData.ImageCount, newData.PublishedAt, newData.RevisionId)
	return err
}

func (m *defaultPostRevisionModel) tableName() string {
	return m.table
}
