// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	postDraftFieldNames          = builder.RawFieldNames(&PostDraft{})
	postDraftRows                = strings.Join(postDraftFieldNames, ",")
	postDraftRowsExpectAutoSet   = strings.Join(stringx.Remove(postDraftFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	postDraftRowsWithPlaceHolder = strings.Join(stringx.Remove(postDraftFieldNames, "`post_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	postDraftModel interface {
		Insert(ctx context.Context, data *PostDraft) (sql.Result, error)
		FindOne(ctx context.Context, postId string) (*PostDraft, error)
		Update(ctx context.Context, data *PostDraft) error
		Delete(ctx context.Context, postId string) error
	}

	defaultPostDraftModel struct {
		conn  sqlx.SqlConn
		table string
	}

	PostDraft struct {
		PostId                string          `db:"post_id"`
		DraftVersion          uint64          `db:"draft_version"`
		LastSaveRequestId     string          `db:"last_save_request_id"`
		Title                 string          `db:"title"`
		Summary               string          `db:"summary"`
		CoverAssetId          sql.NullString  `db:"cover_asset_id"`
		CoverFocusX           sql.NullFloat64 `db:"cover_focus_x"`
		CoverFocusY           sql.NullFloat64 `db:"cover_focus_y"`
		CoverCropStyle        string          `db:"cover_crop_style"`
		PresentationMode      uint64          `db:"presentation_mode"` // 1 traditional, 2 route
		DocumentSchemaVersion uint64          `db:"document_schema_version"`
		DocumentJson          string          `db:"document_json"`
		TagNamesJson          string          `db:"tag_names_json"`
		RouteDraftId          sql.NullString  `db:"route_draft_id"`
		RouteDraftVersion     sql.NullInt64   `db:"route_draft_version"`
		PlainText             string          `db:"plain_text"`
		BlockCount            uint64          `db:"block_count"`
		ImageCount            uint64          `db:"image_count"`
		CreatedAt             time.Time       `db:"created_at"`
		UpdatedAt             time.Time       `db:"updated_at"`
	}
)

func newPostDraftModel(conn sqlx.SqlConn) *defaultPostDraftModel {
	return &defaultPostDraftModel{
		conn:  conn,
		table: "`post_draft`",
	}
}

func (m *defaultPostDraftModel) Delete(ctx context.Context, postId string) error {
	query := fmt.Sprintf("delete from %s where `post_id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, postId)
	return err
}

func (m *defaultPostDraftModel) FindOne(ctx context.Context, postId string) (*PostDraft, error) {
	query := fmt.Sprintf("select %s from %s where `post_id` = ? limit 1", postDraftRows, m.table)
	var resp PostDraft
	err := m.conn.QueryRowCtx(ctx, &resp, query, postId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPostDraftModel) Insert(ctx context.Context, data *PostDraft) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, postDraftRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.PostId, data.DraftVersion, data.LastSaveRequestId, data.Title, data.Summary, data.CoverAssetId, data.CoverFocusX, data.CoverFocusY, data.CoverCropStyle, data.PresentationMode, data.DocumentSchemaVersion, data.DocumentJson, data.TagNamesJson, data.RouteDraftId, data.RouteDraftVersion, data.PlainText, data.BlockCount, data.ImageCount)
	return ret, err
}

func (m *defaultPostDraftModel) Update(ctx context.Context, data *PostDraft) error {
	query := fmt.Sprintf("update %s set %s where `post_id` = ?", m.table, postDraftRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.DraftVersion, data.LastSaveRequestId, data.Title, data.Summary, data.CoverAssetId, data.CoverFocusX, data.CoverFocusY, data.CoverCropStyle, data.PresentationMode, data.DocumentSchemaVersion, data.DocumentJson, data.TagNamesJson, data.RouteDraftId, data.RouteDraftVersion, data.PlainText, data.BlockCount, data.ImageCount, data.PostId)
	return err
}

func (m *defaultPostDraftModel) tableName() string {
	return m.table
}
