// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	postCardProjectionFieldNames          = builder.RawFieldNames(&PostCardProjection{})
	postCardProjectionRows                = strings.Join(postCardProjectionFieldNames, ",")
	postCardProjectionRowsExpectAutoSet   = strings.Join(stringx.Remove(postCardProjectionFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	postCardProjectionRowsWithPlaceHolder = strings.Join(stringx.Remove(postCardProjectionFieldNames, "`post_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	postCardProjectionModel interface {
		Insert(ctx context.Context, data *PostCardProjection) (sql.Result, error)
		FindOne(ctx context.Context, postId string) (*PostCardProjection, error)
		Update(ctx context.Context, data *PostCardProjection) error
		Delete(ctx context.Context, postId string) error
	}

	defaultPostCardProjectionModel struct {
		conn  sqlx.SqlConn
		table string
	}

	PostCardProjection struct {
		PostId             string         `db:"post_id"`
		RevisionId         string         `db:"revision_id"`
		AuthorId           string         `db:"author_id"`
		Title              string         `db:"title"`
		Summary            string         `db:"summary"`
		CoverAssetId       sql.NullString `db:"cover_asset_id"`
		PresentationMode   uint64         `db:"presentation_mode"`
		RouteSnapshotId    sql.NullString `db:"route_snapshot_id"`
		RouteDayCount      uint64         `db:"route_day_count"`
		RouteNodeCount     uint64         `db:"route_node_count"`
		Visibility         uint64         `db:"visibility"`
		AvailabilityStatus uint64         `db:"availability_status"`
		PublishedAt        time.Time      `db:"published_at"`
		SourcePostVersion  uint64         `db:"source_post_version"`
		UpdatedAt          time.Time      `db:"updated_at"`
	}
)

func newPostCardProjectionModel(conn sqlx.SqlConn) *defaultPostCardProjectionModel {
	return &defaultPostCardProjectionModel{
		conn:  conn,
		table: "`post_card_projection`",
	}
}

func (m *defaultPostCardProjectionModel) Delete(ctx context.Context, postId string) error {
	query := fmt.Sprintf("delete from %s where `post_id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, postId)
	return err
}

func (m *defaultPostCardProjectionModel) FindOne(ctx context.Context, postId string) (*PostCardProjection, error) {
	query := fmt.Sprintf("select %s from %s where `post_id` = ? limit 1", postCardProjectionRows, m.table)
	var resp PostCardProjection
	err := m.conn.QueryRowCtx(ctx, &resp, query, postId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPostCardProjectionModel) Insert(ctx context.Context, data *PostCardProjection) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, postCardProjectionRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.PostId, data.RevisionId, data.AuthorId, data.Title, data.Summary, data.CoverAssetId, data.PresentationMode, data.RouteSnapshotId, data.RouteDayCount, data.RouteNodeCount, data.Visibility, data.AvailabilityStatus, data.PublishedAt, data.SourcePostVersion)
	return ret, err
}

func (m *defaultPostCardProjectionModel) Update(ctx context.Context, data *PostCardProjection) error {
	query := fmt.Sprintf("update %s set %s where `post_id` = ?", m.table, postCardProjectionRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.RevisionId, data.AuthorId, data.Title, data.Summary, data.CoverAssetId, data.PresentationMode, data.RouteSnapshotId, data.RouteDayCount, data.RouteNodeCount, data.Visibility, data.AvailabilityStatus, data.PublishedAt, data.SourcePostVersion, data.PostId)
	return err
}

func (m *defaultPostCardProjectionModel) tableName() string {
	return m.table
}
