// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	tagFieldNames          = builder.RawFieldNames(&Tag{})
	tagRows                = strings.Join(tagFieldNames, ",")
	tagRowsExpectAutoSet   = strings.Join(stringx.Remove(tagFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	tagRowsWithPlaceHolder = strings.Join(stringx.Remove(tagFieldNames, "`tag_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	tagModel interface {
		Insert(ctx context.Context, data *Tag) (sql.Result, error)
		FindOne(ctx context.Context, tagId string) (*Tag, error)
		FindOneByNormalizedName(ctx context.Context, normalizedName string) (*Tag, error)
		Update(ctx context.Context, data *Tag) error
		Delete(ctx context.Context, tagId string) error
	}

	defaultTagModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Tag struct {
		TagId          string    `db:"tag_id"`
		NormalizedName string    `db:"normalized_name"`
		DisplayName    string    `db:"display_name"`
		Status         uint64    `db:"status"` // 1 active, 2 hidden, 3 disabled
		CreatedBy      string    `db:"created_by"`
		CreatedAt      time.Time `db:"created_at"`
		UpdatedAt      time.Time `db:"updated_at"`
	}
)

func newTagModel(conn sqlx.SqlConn) *defaultTagModel {
	return &defaultTagModel{
		conn:  conn,
		table: "`tag`",
	}
}

func (m *defaultTagModel) Delete(ctx context.Context, tagId string) error {
	query := fmt.Sprintf("delete from %s where `tag_id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, tagId)
	return err
}

func (m *defaultTagModel) FindOne(ctx context.Context, tagId string) (*Tag, error) {
	query := fmt.Sprintf("select %s from %s where `tag_id` = ? limit 1", tagRows, m.table)
	var resp Tag
	err := m.conn.QueryRowCtx(ctx, &resp, query, tagId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTagModel) FindOneByNormalizedName(ctx context.Context, normalizedName string) (*Tag, error) {
	var resp Tag
	query := fmt.Sprintf("select %s from %s where `normalized_name` = ? limit 1", tagRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, normalizedName)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTagModel) Insert(ctx context.Context, data *Tag) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, tagRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.TagId, data.NormalizedName, data.DisplayName, data.Status, data.CreatedBy)
	return ret, err
}

func (m *defaultTagModel) Update(ctx context.Context, newData *Tag) error {
	query := fmt.Sprintf("update %s set %s where `tag_id` = ?", m.table, tagRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.NormalizedName, newData.DisplayName, newData.Status, newData.CreatedBy, newData.TagId)
	return err
}

func (m *defaultTagModel) tableName() string {
	return m.table
}
