// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userDevicesFieldNames          = builder.RawFieldNames(&UserDevices{})
	userDevicesRows                = strings.Join(userDevicesFieldNames, ",")
	userDevicesRowsExpectAutoSet   = strings.Join(stringx.Remove(userDevicesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	userDevicesRowsWithPlaceHolder = strings.Join(stringx.Remove(userDevicesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	userDevicesModel interface {
		Insert(ctx context.Context, data *UserDevices) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*UserDevices, error)
		FindOneByUserIdDeviceId(ctx context.Context, userId string, deviceId string) (*UserDevices, error)
		Update(ctx context.Context, data *UserDevices) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultUserDevicesModel struct {
		conn  sqlx.SqlConn
		table string
	}

	UserDevices struct {
		Id           uint64    `db:"id"`
		UserId       string    `db:"user_id"`
		DeviceId     string    `db:"device_id"`
		DeviceName   string    `db:"device_name"`
		Platform     string    `db:"platform"`
		AppVersion   string    `db:"app_version"`
		FirstLoginAt time.Time `db:"first_login_at"`
		LastLoginAt  time.Time `db:"last_login_at"`
		Status       uint64    `db:"status"`
	}
)

func newUserDevicesModel(conn sqlx.SqlConn) *defaultUserDevicesModel {
	return &defaultUserDevicesModel{
		conn:  conn,
		table: "`user_devices`",
	}
}

func (m *defaultUserDevicesModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultUserDevicesModel) FindOne(ctx context.Context, id uint64) (*UserDevices, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userDevicesRows, m.table)
	var resp UserDevices
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserDevicesModel) FindOneByUserIdDeviceId(ctx context.Context, userId string, deviceId string) (*UserDevices, error) {
	var resp UserDevices
	query := fmt.Sprintf("select %s from %s where `user_id` = ? and `device_id` = ? limit 1", userDevicesRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, userId, deviceId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserDevicesModel) Insert(ctx context.Context, data *UserDevices) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?)", m.table, userDevicesRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.DeviceId, data.DeviceName, data.Platform, data.AppVersion, data.FirstLoginAt, data.LastLoginAt, data.Status)
	return ret, err
}

func (m *defaultUserDevicesModel) Update(ctx context.Context, newData *UserDevices) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userDevicesRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.UserId, newData.DeviceId, newData.DeviceName, newData.Platform, newData.AppVersion, newData.FirstLoginAt, newData.LastLoginAt, newData.Status, newData.Id)
	return err
}

func (m *defaultUserDevicesModel) tableName() string {
	return m.table
}
