// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userSessionsFieldNames          = builder.RawFieldNames(&UserSessions{})
	userSessionsRows                = strings.Join(userSessionsFieldNames, ",")
	userSessionsRowsExpectAutoSet   = strings.Join(stringx.Remove(userSessionsFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	userSessionsRowsWithPlaceHolder = strings.Join(stringx.Remove(userSessionsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	userSessionsModel interface {
		Insert(ctx context.Context, data *UserSessions) (sql.Result, error)
		FindOne(ctx context.Context, id string) (*UserSessions, error)
		Update(ctx context.Context, data *UserSessions) error
		Delete(ctx context.Context, id string) error
	}

	defaultUserSessionsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	UserSessions struct {
		Id                  string         `db:"id"` // 后端生成的Session UUID
		UserId              string         `db:"user_id"`
		DeviceId            string         `db:"device_id"`
		Status              uint64         `db:"status"` // 0=已失效，1=正常使用
		CreatedAt           time.Time      `db:"created_at"`
		RefreshedAt         time.Time      `db:"refreshed_at"`
		NotAfter            time.Time      `db:"not_after"` // Session最晚有效时间
		RefreshTokenKey     string         `db:"refresh_token_key"`
		RefreshTokenCounter uint64         `db:"refresh_token_counter"`
		RevokedAt           sql.NullTime   `db:"revoked_at"`
		RevokeReason        sql.NullString `db:"revoke_reason"`
		UpdatedAt           time.Time      `db:"updated_at"`
	}
)

func newUserSessionsModel(conn sqlx.SqlConn) *defaultUserSessionsModel {
	return &defaultUserSessionsModel{
		conn:  conn,
		table: "`user_sessions`",
	}
}

func (m *defaultUserSessionsModel) Delete(ctx context.Context, id string) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultUserSessionsModel) FindOne(ctx context.Context, id string) (*UserSessions, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userSessionsRows, m.table)
	var resp UserSessions
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserSessionsModel) Insert(ctx context.Context, data *UserSessions) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, userSessionsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.UserId, data.DeviceId, data.Status, data.RefreshedAt, data.NotAfter, data.RefreshTokenKey, data.RefreshTokenCounter, data.RevokedAt, data.RevokeReason)
	return ret, err
}

func (m *defaultUserSessionsModel) Update(ctx context.Context, data *UserSessions) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userSessionsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.UserId, data.DeviceId, data.Status, data.RefreshedAt, data.NotAfter, data.RefreshTokenKey, data.RefreshTokenCounter, data.RevokedAt, data.RevokeReason, data.Id)
	return err
}

func (m *defaultUserSessionsModel) tableName() string {
	return m.table
}
