// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2

package handler

import (
	"net/http"

	"contentserver/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/health",
				Handler: HealthHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/posts",
				Handler: ListPostsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/posts/:postId",
				Handler: GetPostHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/ready",
				Handler: ReadinessHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/tags/search",
				Handler: SearchTagsHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/me/posts",
				Handler: ListMyPostsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/media/assets",
				Handler: CreateImageUploadHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/media/assets/:assetId",
				Handler: DeleteMediaAssetHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/media/assets/:assetId/complete",
				Handler: CompleteImageUploadHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/posts",
				Handler: CreatePostHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/posts/:postId",
				Handler: DeletePostHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/posts/:postId/draft",
				Handler: GetPostDraftHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/posts/:postId/draft",
				Handler: SavePostDraftHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/posts/:postId/publish",
				Handler: PublishPostHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/posts/:postId/route-draft",
				Handler: CreatePostRouteDraftHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/posts/:postId/route-draft",
				Handler: DetachPostRouteDraftHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/posts/:postId/visibility",
				Handler: ChangePostVisibilityHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1"),
	)
}
