// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2

package handler

import (
	"net/http"

	"contentserver/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/health",
				Handler: HealthHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/me/posts",
				Handler: ListMyPostsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/posts",
				Handler: CreatePostHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/posts",
				Handler: ListPostsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/posts/:postId",
				Handler: GetPostHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/posts/:postId",
				Handler: UpdatePostHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/posts/:postId",
				Handler: DeletePostHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/posts/:postId/publish",
				Handler: PublishPostHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/posts/:postId/visibility",
				Handler: ChangePostVisibilityHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)
}
